services:
  - type: web
    name: data-hub-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        value: https://*.onrender.com,http://localhost:3000
      - key: APP_BASE_URL
        value: https://data-hub-6kwj.onrender.com
      - key: PAYMENT_PROVIDER
        value: SIMULATED
      - key: PAYMENT_CALLBACK_TOKEN
        sync: false
      - key: PAYMENT_CALLBACK_PROVIDER
        value: AUTO
      - key: VTU_PROVIDER
        value: SIMULATED
      - key: ADMIN_EMAIL
        sync: false
