services:
  - type: web
    name: data-hub-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: CORS_ORIGIN
        value: "http://localhost:3000,https://data-hub-1-m4o4.onrender.com,https://data-hub-6kwj.onrender.com"
      - key: PAYMENT_PROVIDER
        value: "SIMULATED"
      - key: PAYMENT_CALLBACK_PROVIDER
        value: "AUTO"
      - key: HUBTEL_BASE_URL
        value: "https://api.hubtel.com"
      - key: HUBTEL_SMS_BASE_URL
        value: "https://smsc.hubtel.com/v1/messages/send"
      - key: HUBTEL_SMS_FROM
        value: "Prosperous"
      - key: VTU_PROVIDER
        value: "SIMULATED"
      - key: SMTP_FROM_NAME
        value: "Prosperous Data Hub"
